name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dart
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v3
      - run: dart --version
      - name: Install dependencies
        run: dart pub get && dart pub global activate dart_frog_cli && dart_frog build
      - name: Pushing to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "smart-plants-dart"
          heroku_email: "gab.costache@gmail.com"
          usedocker: true
          appdir: build
      - name: Print version again
      - run: dart --version
