name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print secrets
        run: |
          echo $APP_CONFIG &gt;&gt; ./config.yaml

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "smart-plants-dart"
          heroku_email: "gab.costache@gmail.com"
          usedocker: true
          dontuseforce: 1
